version: '3.3'

services: 
    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
        ports: 
            - "${MONGO_PORT}:27017"
        networks:
            - kanban_app

    rabbit-mq:
        image: rabbitmq:3-management
        hostname: some-rabbit
        ports: 
            - "15672:15672"
            - "5672:5672"
        networks:
            - kanban_app

    docs:
        image: docs
        build: 
            context: ./collections
        ports: 
            - "${DOCS_PORT}:5000"
        networks:
            - kanban_app
networks:
  kanban_app:
      driver: bridge
      name: kanban_app 