version: '3.3'

services: 
    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
        ports: 
            - "${MONGO_PORT}:27017"
        networks:
            - kanban

    kanbanapp:
        image: kanban-app
        build: 
            context: .
        ports: 
            - "${PORT}:1747"
        links:
            - mongo
        networks:
            - kanban

    docs:
        image: docs
        build: 
            context: ./collections
        ports: 
            - "${DOCS_PORT}:5000"
        networks:
            - kanban
networks:
  kanban:
      driver: overlay
      name: kanban 
      # if your are not using kanban gateway to deploy the application
      # just comment the last two lines of this docker-compose file ..
      external: 
        name: kanban
