version: '3.3'

services: 
    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=kevindasilva
            - MONGO_INITDB_ROOT_PASSWORD=123
            - MONGO_INITDB_DATABASE=admin
        ports: 
            - "27017:27017"

    kanbanapp:
        image: kanban-app
        build: 
            context: .
        ports: 
            - "1747:1747"
        links:
            - mongo

    docs:
        image: docs
        build: 
            context: ./collections
        ports: 
            - "5000:5000"
