version: '3.3'

services: 
    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
        ports: 
            - "${MONGO_PORT}:27017"

    kanbanapp:
        image: kanban-app
        build: 
            context: .
        ports: 
            - "${PORT}:1747"
        links:
            - mongo

    docs:
        image: docs
        build: 
            context: ./collections
        ports: 
            - "${DOCS_PORT}:5000"
