version: '3.3'

services: 
    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
        ports: 
            - "${MONGO_PORT}:27017"
        networks:
            - kanban_app

    kanbanapp:
        image: kanban-app
        environment: 
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
            - RABBIT_HOST=${RABBIT_HOST}
        build: 
            context: .
        ports: 
            - "${PORT}:1747"
        links:
            - mongo
        networks:
            - kanban
            - kanban_app

    docs:
        image: docs
        build: 
            context: ./collections
        ports: 
            - "${DOCS_PORT}:5000"
        networks:
            #- kanban
            - kanban_app
networks:
  kanban_app:
      driver: bridge
      name: kanban_app 
# if your are not using kanban gateway to deploy the application
# just comment all the kanban network references in this docker-compose file ..
  kanban:
      driver: overlay
      external: 
        name: eg-gateway_kanban
